export const dummyEvents = [
  {
    id: "1",
    imageUrl: "/hero/e1.jpg",
    title: "Tech Innovators Summit",
    type: "Event",
    clubName: "Coding Club",
    venue: "Main Auditorium",
    date: "May 18, 2025",
    participants: 120,
    isRegistered: false,
  },
  {
    id: "2",
    imageUrl: "/hero/b2.jpg",
    title: "AI & ML Hands-on Workshop",
    type: "Workshop",
    clubName: "AI Club",
    venue: "Lab 3, Block B",
    date: "May 22, 2025",
    participants: 60,
    isRegistered: true,
  },
  {
    id: "3",
    imageUrl: "/hero/o1.jpg",
    title: "Nature Photowalk",
    type: "Event",
    clubName: "Photography Club",
    venue: "Botanical Garden",
    date: "May 25, 2025",
    participants: 34,
    isRegistered: false,
  },
  {
    id: "4",
    imageUrl: "/hero/p1.jpg",
    title: "Health Awareness Talk",
    type: "Event",
    clubName: "Health & Wellness Club",
    venue: "Seminar Hall 2",
    date: "May 12, 2025",
    participants: 89,
    isRegistered: true,
  },
  {
    id: "5",
    imageUrl: "/hero/c1.jpg",
    title: "Startup Bootcamp",
    type: "Workshop",
    clubName: "Entrepreneurship Cell",
    venue: "Innovation Lab",
    date: "May 30, 2025",
    participants: 102,
    isRegistered: false,
  },
];

export const dummyTop3Events = [
  {
    id: "1",
    imageUrl: "/hero/e1.jpg",
    title: "Tech Innovators Summit",
    type: "Event",
    clubName: "Coding Club",
    venue: "Main Auditorium",
    date: "May 18, 2025",
    participants: 120,
    isRegistered: false,
  },
  {
    id: "2",
    imageUrl: "/hero/o1.jpg",
    title: "AI & ML Hands-on Workshop",
    type: "Workshop",
    clubName: "AI Club",
    venue: "Lab 3, Block B",
    date: "May 22, 2025",
    participants: 60,
    isRegistered: true,
  },
  {
    id: "3",
    imageUrl: "/hero/c1.jpg",
    title: "Nature Photowalk",
    type: "Event",
    clubName: "Photography Club",
    venue: "Botanical Garden",
    date: "May 25, 2025",
    participants: 34,
    isRegistered: false,
  },
];

export const dummyFlashEvents = [
  {
    eventId: "techx23",
    imageUrl: "/hero/c1.jpg",
    title: "TechXplosion 2025",
    type: "Event",
    clubName: "Innovators Club",
    venue: "Main Auditorium",
    date: "May 10, 2025",
    participants: 156,
  },
  {
    eventId: "aiworkshop",
    imageUrl: "/hero/e1.jpg",
    title: "Hands-on AI with Python",
    type: "Workshop",
    clubName: "CodeCraft Club",
    venue: "Lab 5, CSE Block",
    date: "May 15, 2025",
    participants: 78,
  },
  {
    eventId: "bizpitch25",
    imageUrl: "/hero/b1.jpeg",
    title: "BizPitch Battle Royale",
    type: "Event",
    clubName: "Entrepreneurship Cell",
    venue: "Seminar Hall B",
    date: "May 20, 2025",
    participants: 134,
  },
];

// suggeted events
export const suggestedEvents = [
  {
    id: "1",
    name: "TechXplosion 2025: Exploring the Future of Innovation",
  },
  {
    id: "2",
    name: "Creative Minds Meetup: Designing Tomorrow’s Interfaces",
  },
  {
    id: "3",
    name: "Sustainable Solutions Summit: Green Tech for a Better World",
  },
  {
    id: "4",
    name: "AI and Ethics Symposium: Building Responsible Intelligence",
  },
];
